plugins:
  sign_in_with_apple_enabled:
    client: true
    default: false
  apple_client_id:
    client: false
    default: ''
  apple_team_id:
    client: false
    default: ''
  apple_key_id:
    client: false
    default: ''
  apple_pem:
    client: false
    default: ''
  apple_verification_txt:
    default: ''
    textarea: true
